// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm-HN46LhdmeZjV1OqUp6d8h0MNFin0Cc',
    appId: '1:229626012516:web:5e35af3d3f479c19639071',
    messagingSenderId: '229626012516',
    projectId: 'crazy-bankers-01928',
    authDomain: 'crazy-bankers-01928.firebaseapp.com',
    storageBucket: 'crazy-bankers-01928.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7K1UMn-9pUbkcbpHEDBfs5U17fwAosJM',
    appId: '1:229626012516:android:28a5939c40117b40639071',
    messagingSenderId: '229626012516',
    projectId: 'crazy-bankers-01928',
    storageBucket: 'crazy-bankers-01928.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDznIBlTwHefbQqLhs0pIC2mIx9jDYdTcQ',
    appId: '1:229626012516:ios:303798c42f34b1eb639071',
    messagingSenderId: '229626012516',
    projectId: 'crazy-bankers-01928',
    storageBucket: 'crazy-bankers-01928.firebasestorage.app',
    iosBundleId: 'com.example.crazyBankers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDznIBlTwHefbQqLhs0pIC2mIx9jDYdTcQ',
    appId: '1:229626012516:ios:303798c42f34b1eb639071',
    messagingSenderId: '229626012516',
    projectId: 'crazy-bankers-01928',
    storageBucket: 'crazy-bankers-01928.firebasestorage.app',
    iosBundleId: 'com.example.crazyBankers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm-HN46LhdmeZjV1OqUp6d8h0MNFin0Cc',
    appId: '1:229626012516:web:9583895fa59feada639071',
    messagingSenderId: '229626012516',
    projectId: 'crazy-bankers-01928',
    authDomain: 'crazy-bankers-01928.firebaseapp.com',
    storageBucket: 'crazy-bankers-01928.firebasestorage.app',
  );

}